info:
  title: Goodnut's BLOG
  subtitle: "\u8BB0\u5F55\u6298\u817E\u3001\u5B66\u4E60\u4E0E\u968F\u60F3"
  author: GoodNut
  url: https://ddmaster2608.github.io
defaults:
  favicon: /images/favicon.ico
  logo: /images/logo.jpg
  avatar: /images/avatar.jpg
colors:
  primary: '#A31F34'
  default_mode: light
global:
  website_counter:
    enable: false
    site_pv: false
    site_uv: false
    post_pv: false
  preloader:
    enable: false
  open_graph:
    enable: true
    image: /images/avatar.jpg
    description: "Goodnut \u7684\u535A\u5BA2\uFF0C\u8BB0\u5F55\u6298\u817E\u3001\u5B66\
      \u4E60\u4E0E\u968F\u60F3\u3002"
home_banner:
  enable: true
  style: fixed
  image:
    light: /images/banner-light.jpg
    dark: /images/banner-dark.png
  title: "\u5f53\u65f6\u53ea\u9053\u662f\u5bfb\u5e38"
  subtitle:
    text:
    - Goodnut's Blog
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  social_links:
    enable: true
    style: default
    links:
    - icon: github
      url: https://github.com/ddmaster2608
    - icon: email
      url: mailto:owen238509427@163.com
    - icon: fa-brands fa-bilibili
      url: https://search.bilibili.com/all?keyword=good_nut
navbar:
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Archives:
      path: /archives
      icon: fa-regular fa-box-archive
    Categories:
      path: /categories
      icon: fa-regular fa-folder-open
    Tags:
      path: /tags
      icon: fa-regular fa-tags
  search:
    enable: false
home:
  sidebar:
    enable: true
    position: left
    first_item: info
    announcement: "\u4F17\u91CC\u5BFB\u4ED6\u5343\u767E\u5EA6\uFF0C\u84E6\u7136\u56DE\
      \u9996\uFF0C\u90A3\u4EBA\u5374\u5728\uFF0C\u706F\u706B\u9611\u73CA\u5904"
    show_on_mobile: true
    links:
      Archives:
        path: /archives
        icon: fa-regular fa-box-archive
      Categories:
        path: /categories
        icon: fa-regular fa-folder-open
      Tags:
        path: /tags
        icon: fa-regular fa-tags
articles:
  word_count:
    enable: true
    count: true
    min2read: true
  copyright:
    enable: true
    default: cc_by_nc_sa
comment:
  enable: false
footer:
  runtime: false
  statistics: false
  customize: Goodnut's BLOG
  icp:
    enable: false
plugins:
  feed:
    enable: false
  aplayer:
    enable: false
  mermaid:
    enable: false
inject:
  enable: true
  head:
  - "<style>.home-banner .description,\n.home-banner .description * ,\n.home-sidebar,\n\
    .home-sidebar * ,\n.info-card,\n.info-card * {\n  font-family: 'PingFang SC',\
    \ 'Hiragino Sans GB', 'Microsoft YaHei', 'Noto Sans CJK SC', 'Source Han Sans\
    \ SC', 'WenQuanYi Micro Hei', sans-serif !important;\n}</style>"
