info:
  title: Goodnut's BLOG
  subtitle: 记录折腾、学习与随想
  author: GoodNut
  url: https://ddmaster2608.github.io
defaults:
  favicon: /images/favicon.ico
  logo: /images/logo.jpg
  avatar: /images/avatar.jpg
colors:
  primary: '#A31F34'
  default_mode: light
global:
  website_counter:
    enable: false
    site_pv: false
    site_uv: false
    post_pv: false
  preloader:
    enable: false
  open_graph:
    enable: true
    image: /images/avatar.jpg
    description: Goodnut 的博客，记录折腾、学习与随想。
home_banner:
  enable: true
  style: fixed
  image:
    light: /images/banner-light.jpg
    dark: /images/banner-dark.png
  title: 当时只道是寻常
  subtitle:
    text:
    - Goodnut's Blog
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  social_links:
    enable: true
    style: default
    links:
    - icon: github
      url: https://github.com/ddmaster2608
    - icon: email
      url: mailto:owen238509427@163.com
    - icon: fa-brands fa-bilibili
      url: https://space.bilibili.com/511179155?spm_id_from=333.337.0.0
navbar:
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Archives:
      path: /archives
      icon: fa-regular fa-box-archive
    Categories:
      path: /categories
      icon: fa-regular fa-folder-open
    Tags:
      path: /tags
      icon: fa-regular fa-tags
  search:
    enable: false
home:
  sidebar:
    enable: true
    position: left
    first_item: info
    announcement: 众里寻他千百度，蓦然回首，那人却在，灯火阑珊处
    show_on_mobile: true
    links:
      Archives:
        path: /archives
        icon: fa-regular fa-box-archive
      Categories:
        path: /categories
        icon: fa-regular fa-folder-open
      Tags:
        path: /tags
        icon: fa-regular fa-tags
articles:
  word_count:
    enable: true
    count: true
    min2read: true
  copyright:
    enable: true
    default: cc_by_nc_sa
comment:
  enable: true
  system: artalk
  config:
    artalk:
      server: https://artalk.118-25-154-200.sslip.io
      site: Goodnut's Blog
footer:
  runtime: false
  statistics: false
  customize: Goodnut's BLOG
  icp:
    enable: false
plugins:
  feed:
    enable: false
  aplayer:
    enable: false
  mermaid:
    enable: false
inject:
  enable: true
  head:
  - "<style>.home-banner .description,\n.home-banner .description * ,\n.home-sidebar,\n\
    .home-sidebar * ,\n.info-card,\n.info-card * {\n  font-family: 'PingFang SC',\
    \ 'Hiragino Sans GB', 'Microsoft YaHei', 'Noto Sans CJK SC', 'Source Han Sans\
    \ SC', 'WenQuanYi Micro Hei', sans-serif !important;\n}</style>"
